import { Metadata } from "next";

export const metadata: Metadata = {
    title: {
      default: "Next.js Learning",
      template: "%s | Next.js Learning",
    },
    description: 'Generated by Next.js',
  }
  

export default function Home() {
    return (
        <>
        <h1>Home Page</h1>
        </>
    )
}