export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "50px 10px" }}>
          Header
        </header>
        <main>
          {children}
        </main>
        <footer style={{ backgroundColor: "lightgrey", padding: "50px 10px" }}>
          Footer
        </footer>
      </body>
    </html>
  )
}
